import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {type: 'autogenerated', dirName: 'kom-i-gang'},
    {type: 'autogenerated', dirName: 'tiltakslopet'},
    {type: 'autogenerated', dirName: 'plan'},
    {type: 'autogenerated', dirName: 'metodikk'},
    {type: 'autogenerated', dirName: 'samarbeid'},
    {type: 'autogenerated', dirName: 'verktoy'},
    {type: 'autogenerated', dirName: 'regelverk'},
    {type: 'autogenerated', dirName: 'fordypning'},
  ],
};

export default sidebars;
